// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddBudgetReducer from "../add_budget_reducer";
import AddUserReducer from "../add_user_reducer";

export type AddBudgetParams = __Infer<typeof AddBudgetReducer>;
export type AddUserParams = __Infer<typeof AddUserReducer>;

