/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BudgetPlansIndexRouteImport } from './routes/budgetPlans/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoOrpcTodoRouteImport } from './routes/demo/orpc-todo'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as ApiFinancialAccountsRouteImport } from './routes/api/financialAccounts'
import { Route as ApiBudgetsRouteImport } from './routes/api/budgets'
import { Route as ApiBudgetPlansRouteImport } from './routes/api/budgetPlans'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as BudgetPlansBudgetPlanIdRouteRouteImport } from './routes/budgetPlans/$budgetPlanId/route'
import { Route as BudgetPlansBudgetPlanIdIndexRouteImport } from './routes/budgetPlans/$budgetPlanId/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as BudgetPlansBudgetPlanIdAccountsIndexRouteImport } from './routes/budgetPlans/$budgetPlanId/accounts/index'
import { Route as BudgetPlansBudgetPlanIdAccountsAccountIdRouteImport } from './routes/budgetPlans/$budgetPlanId/accounts/$accountId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetPlansIndexRoute = BudgetPlansIndexRouteImport.update({
  id: '/budgetPlans/',
  path: '/budgetPlans/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOrpcTodoRoute = DemoOrpcTodoRouteImport.update({
  id: '/demo/orpc-todo',
  path: '/demo/orpc-todo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinancialAccountsRoute = ApiFinancialAccountsRouteImport.update({
  id: '/api/financialAccounts',
  path: '/api/financialAccounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBudgetsRoute = ApiBudgetsRouteImport.update({
  id: '/api/budgets',
  path: '/api/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBudgetPlansRoute = ApiBudgetPlansRouteImport.update({
  id: '/api/budgetPlans',
  path: '/api/budgetPlans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetPlansBudgetPlanIdRouteRoute =
  BudgetPlansBudgetPlanIdRouteRouteImport.update({
    id: '/budgetPlans/$budgetPlanId',
    path: '/budgetPlans/$budgetPlanId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BudgetPlansBudgetPlanIdIndexRoute =
  BudgetPlansBudgetPlanIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BudgetPlansBudgetPlanIdRouteRoute,
  } as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetPlansBudgetPlanIdAccountsIndexRoute =
  BudgetPlansBudgetPlanIdAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => BudgetPlansBudgetPlanIdRouteRoute,
  } as any)
const BudgetPlansBudgetPlanIdAccountsAccountIdRoute =
  BudgetPlansBudgetPlanIdAccountsAccountIdRouteImport.update({
    id: '/accounts/$accountId',
    path: '/accounts/$accountId',
    getParentRoute: () => BudgetPlansBudgetPlanIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budgetPlans/$budgetPlanId': typeof BudgetPlansBudgetPlanIdRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/budgetPlans': typeof ApiBudgetPlansRoute
  '/api/budgets': typeof ApiBudgetsRoute
  '/api/financialAccounts': typeof ApiFinancialAccountsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/budgetPlans/': typeof BudgetPlansIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/budgetPlans/$budgetPlanId/': typeof BudgetPlansBudgetPlanIdIndexRoute
  '/budgetPlans/$budgetPlanId/accounts/$accountId': typeof BudgetPlansBudgetPlanIdAccountsAccountIdRoute
  '/budgetPlans/$budgetPlanId/accounts/': typeof BudgetPlansBudgetPlanIdAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/api/budgetPlans': typeof ApiBudgetPlansRoute
  '/api/budgets': typeof ApiBudgetsRoute
  '/api/financialAccounts': typeof ApiFinancialAccountsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/budgetPlans': typeof BudgetPlansIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/budgetPlans/$budgetPlanId': typeof BudgetPlansBudgetPlanIdIndexRoute
  '/budgetPlans/$budgetPlanId/accounts/$accountId': typeof BudgetPlansBudgetPlanIdAccountsAccountIdRoute
  '/budgetPlans/$budgetPlanId/accounts': typeof BudgetPlansBudgetPlanIdAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budgetPlans/$budgetPlanId': typeof BudgetPlansBudgetPlanIdRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/budgetPlans': typeof ApiBudgetPlansRoute
  '/api/budgets': typeof ApiBudgetsRoute
  '/api/financialAccounts': typeof ApiFinancialAccountsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/budgetPlans/': typeof BudgetPlansIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/budgetPlans/$budgetPlanId/': typeof BudgetPlansBudgetPlanIdIndexRoute
  '/budgetPlans/$budgetPlanId/accounts/$accountId': typeof BudgetPlansBudgetPlanIdAccountsAccountIdRoute
  '/budgetPlans/$budgetPlanId/accounts/': typeof BudgetPlansBudgetPlanIdAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budgetPlans/$budgetPlanId'
    | '/api/$'
    | '/api/budgetPlans'
    | '/api/budgets'
    | '/api/financialAccounts'
    | '/demo/better-auth'
    | '/demo/orpc-todo'
    | '/demo/tanstack-query'
    | '/budgetPlans/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/budgetPlans/$budgetPlanId/'
    | '/budgetPlans/$budgetPlanId/accounts/$accountId'
    | '/budgetPlans/$budgetPlanId/accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/api/budgetPlans'
    | '/api/budgets'
    | '/api/financialAccounts'
    | '/demo/better-auth'
    | '/demo/orpc-todo'
    | '/demo/tanstack-query'
    | '/budgetPlans'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/budgetPlans/$budgetPlanId'
    | '/budgetPlans/$budgetPlanId/accounts/$accountId'
    | '/budgetPlans/$budgetPlanId/accounts'
  id:
    | '__root__'
    | '/'
    | '/budgetPlans/$budgetPlanId'
    | '/api/$'
    | '/api/budgetPlans'
    | '/api/budgets'
    | '/api/financialAccounts'
    | '/demo/better-auth'
    | '/demo/orpc-todo'
    | '/demo/tanstack-query'
    | '/budgetPlans/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/budgetPlans/$budgetPlanId/'
    | '/budgetPlans/$budgetPlanId/accounts/$accountId'
    | '/budgetPlans/$budgetPlanId/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetPlansBudgetPlanIdRouteRoute: typeof BudgetPlansBudgetPlanIdRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiBudgetPlansRoute: typeof ApiBudgetPlansRoute
  ApiBudgetsRoute: typeof ApiBudgetsRoute
  ApiFinancialAccountsRoute: typeof ApiFinancialAccountsRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoOrpcTodoRoute: typeof DemoOrpcTodoRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  BudgetPlansIndexRoute: typeof BudgetPlansIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgetPlans/': {
      id: '/budgetPlans/'
      path: '/budgetPlans'
      fullPath: '/budgetPlans/'
      preLoaderRoute: typeof BudgetPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/orpc-todo': {
      id: '/demo/orpc-todo'
      path: '/demo/orpc-todo'
      fullPath: '/demo/orpc-todo'
      preLoaderRoute: typeof DemoOrpcTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/financialAccounts': {
      id: '/api/financialAccounts'
      path: '/api/financialAccounts'
      fullPath: '/api/financialAccounts'
      preLoaderRoute: typeof ApiFinancialAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/budgets': {
      id: '/api/budgets'
      path: '/api/budgets'
      fullPath: '/api/budgets'
      preLoaderRoute: typeof ApiBudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/budgetPlans': {
      id: '/api/budgetPlans'
      path: '/api/budgetPlans'
      fullPath: '/api/budgetPlans'
      preLoaderRoute: typeof ApiBudgetPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgetPlans/$budgetPlanId': {
      id: '/budgetPlans/$budgetPlanId'
      path: '/budgetPlans/$budgetPlanId'
      fullPath: '/budgetPlans/$budgetPlanId'
      preLoaderRoute: typeof BudgetPlansBudgetPlanIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgetPlans/$budgetPlanId/': {
      id: '/budgetPlans/$budgetPlanId/'
      path: '/'
      fullPath: '/budgetPlans/$budgetPlanId/'
      preLoaderRoute: typeof BudgetPlansBudgetPlanIdIndexRouteImport
      parentRoute: typeof BudgetPlansBudgetPlanIdRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgetPlans/$budgetPlanId/accounts/': {
      id: '/budgetPlans/$budgetPlanId/accounts/'
      path: '/accounts'
      fullPath: '/budgetPlans/$budgetPlanId/accounts/'
      preLoaderRoute: typeof BudgetPlansBudgetPlanIdAccountsIndexRouteImport
      parentRoute: typeof BudgetPlansBudgetPlanIdRouteRoute
    }
    '/budgetPlans/$budgetPlanId/accounts/$accountId': {
      id: '/budgetPlans/$budgetPlanId/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/budgetPlans/$budgetPlanId/accounts/$accountId'
      preLoaderRoute: typeof BudgetPlansBudgetPlanIdAccountsAccountIdRouteImport
      parentRoute: typeof BudgetPlansBudgetPlanIdRouteRoute
    }
  }
}

interface BudgetPlansBudgetPlanIdRouteRouteChildren {
  BudgetPlansBudgetPlanIdIndexRoute: typeof BudgetPlansBudgetPlanIdIndexRoute
  BudgetPlansBudgetPlanIdAccountsAccountIdRoute: typeof BudgetPlansBudgetPlanIdAccountsAccountIdRoute
  BudgetPlansBudgetPlanIdAccountsIndexRoute: typeof BudgetPlansBudgetPlanIdAccountsIndexRoute
}

const BudgetPlansBudgetPlanIdRouteRouteChildren: BudgetPlansBudgetPlanIdRouteRouteChildren =
  {
    BudgetPlansBudgetPlanIdIndexRoute: BudgetPlansBudgetPlanIdIndexRoute,
    BudgetPlansBudgetPlanIdAccountsAccountIdRoute:
      BudgetPlansBudgetPlanIdAccountsAccountIdRoute,
    BudgetPlansBudgetPlanIdAccountsIndexRoute:
      BudgetPlansBudgetPlanIdAccountsIndexRoute,
  }

const BudgetPlansBudgetPlanIdRouteRouteWithChildren =
  BudgetPlansBudgetPlanIdRouteRoute._addFileChildren(
    BudgetPlansBudgetPlanIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetPlansBudgetPlanIdRouteRoute:
    BudgetPlansBudgetPlanIdRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiBudgetPlansRoute: ApiBudgetPlansRoute,
  ApiBudgetsRoute: ApiBudgetsRoute,
  ApiFinancialAccountsRoute: ApiFinancialAccountsRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoOrpcTodoRoute: DemoOrpcTodoRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  BudgetPlansIndexRoute: BudgetPlansIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
