/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BudgetsIndexRouteImport } from './routes/budgets/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoOrpcTodoRouteImport } from './routes/demo/orpc-todo'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as ApiFinancialAccountsRouteImport } from './routes/api/financialAccounts'
import { Route as ApiBudgetsRouteImport } from './routes/api/budgets'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as BudgetsBudgetIdRouteRouteImport } from './routes/budgets/$budgetId/route'
import { Route as BudgetsBudgetIdIndexRouteImport } from './routes/budgets/$budgetId/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as BudgetsBudgetIdAccountsIndexRouteImport } from './routes/budgets/$budgetId/accounts/index'
import { Route as BudgetsBudgetIdAccountsAccountIdRouteImport } from './routes/budgets/$budgetId/accounts/$accountId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsIndexRoute = BudgetsIndexRouteImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOrpcTodoRoute = DemoOrpcTodoRouteImport.update({
  id: '/demo/orpc-todo',
  path: '/demo/orpc-todo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinancialAccountsRoute = ApiFinancialAccountsRouteImport.update({
  id: '/api/financialAccounts',
  path: '/api/financialAccounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBudgetsRoute = ApiBudgetsRouteImport.update({
  id: '/api/budgets',
  path: '/api/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsBudgetIdRouteRoute = BudgetsBudgetIdRouteRouteImport.update({
  id: '/budgets/$budgetId',
  path: '/budgets/$budgetId',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsBudgetIdIndexRoute = BudgetsBudgetIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BudgetsBudgetIdRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsBudgetIdAccountsIndexRoute =
  BudgetsBudgetIdAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => BudgetsBudgetIdRouteRoute,
  } as any)
const BudgetsBudgetIdAccountsAccountIdRoute =
  BudgetsBudgetIdAccountsAccountIdRouteImport.update({
    id: '/accounts/$accountId',
    path: '/accounts/$accountId',
    getParentRoute: () => BudgetsBudgetIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budgets/$budgetId': typeof BudgetsBudgetIdRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/budgets': typeof ApiBudgetsRoute
  '/api/financialAccounts': typeof ApiFinancialAccountsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/budgets/': typeof BudgetsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/budgets/$budgetId/': typeof BudgetsBudgetIdIndexRoute
  '/budgets/$budgetId/accounts/$accountId': typeof BudgetsBudgetIdAccountsAccountIdRoute
  '/budgets/$budgetId/accounts/': typeof BudgetsBudgetIdAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/api/budgets': typeof ApiBudgetsRoute
  '/api/financialAccounts': typeof ApiFinancialAccountsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/budgets': typeof BudgetsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/budgets/$budgetId': typeof BudgetsBudgetIdIndexRoute
  '/budgets/$budgetId/accounts/$accountId': typeof BudgetsBudgetIdAccountsAccountIdRoute
  '/budgets/$budgetId/accounts': typeof BudgetsBudgetIdAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budgets/$budgetId': typeof BudgetsBudgetIdRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/budgets': typeof ApiBudgetsRoute
  '/api/financialAccounts': typeof ApiFinancialAccountsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/budgets/': typeof BudgetsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/budgets/$budgetId/': typeof BudgetsBudgetIdIndexRoute
  '/budgets/$budgetId/accounts/$accountId': typeof BudgetsBudgetIdAccountsAccountIdRoute
  '/budgets/$budgetId/accounts/': typeof BudgetsBudgetIdAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budgets/$budgetId'
    | '/api/$'
    | '/api/budgets'
    | '/api/financialAccounts'
    | '/demo/better-auth'
    | '/demo/orpc-todo'
    | '/demo/tanstack-query'
    | '/budgets/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/budgets/$budgetId/'
    | '/budgets/$budgetId/accounts/$accountId'
    | '/budgets/$budgetId/accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/api/budgets'
    | '/api/financialAccounts'
    | '/demo/better-auth'
    | '/demo/orpc-todo'
    | '/demo/tanstack-query'
    | '/budgets'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/budgets/$budgetId'
    | '/budgets/$budgetId/accounts/$accountId'
    | '/budgets/$budgetId/accounts'
  id:
    | '__root__'
    | '/'
    | '/budgets/$budgetId'
    | '/api/$'
    | '/api/budgets'
    | '/api/financialAccounts'
    | '/demo/better-auth'
    | '/demo/orpc-todo'
    | '/demo/tanstack-query'
    | '/budgets/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/budgets/$budgetId/'
    | '/budgets/$budgetId/accounts/$accountId'
    | '/budgets/$budgetId/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetsBudgetIdRouteRoute: typeof BudgetsBudgetIdRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiBudgetsRoute: typeof ApiBudgetsRoute
  ApiFinancialAccountsRoute: typeof ApiFinancialAccountsRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoOrpcTodoRoute: typeof DemoOrpcTodoRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  BudgetsIndexRoute: typeof BudgetsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/': {
      id: '/budgets/'
      path: '/budgets'
      fullPath: '/budgets/'
      preLoaderRoute: typeof BudgetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/orpc-todo': {
      id: '/demo/orpc-todo'
      path: '/demo/orpc-todo'
      fullPath: '/demo/orpc-todo'
      preLoaderRoute: typeof DemoOrpcTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/financialAccounts': {
      id: '/api/financialAccounts'
      path: '/api/financialAccounts'
      fullPath: '/api/financialAccounts'
      preLoaderRoute: typeof ApiFinancialAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/budgets': {
      id: '/api/budgets'
      path: '/api/budgets'
      fullPath: '/api/budgets'
      preLoaderRoute: typeof ApiBudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/$budgetId': {
      id: '/budgets/$budgetId'
      path: '/budgets/$budgetId'
      fullPath: '/budgets/$budgetId'
      preLoaderRoute: typeof BudgetsBudgetIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/$budgetId/': {
      id: '/budgets/$budgetId/'
      path: '/'
      fullPath: '/budgets/$budgetId/'
      preLoaderRoute: typeof BudgetsBudgetIdIndexRouteImport
      parentRoute: typeof BudgetsBudgetIdRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/$budgetId/accounts/': {
      id: '/budgets/$budgetId/accounts/'
      path: '/accounts'
      fullPath: '/budgets/$budgetId/accounts/'
      preLoaderRoute: typeof BudgetsBudgetIdAccountsIndexRouteImport
      parentRoute: typeof BudgetsBudgetIdRouteRoute
    }
    '/budgets/$budgetId/accounts/$accountId': {
      id: '/budgets/$budgetId/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/budgets/$budgetId/accounts/$accountId'
      preLoaderRoute: typeof BudgetsBudgetIdAccountsAccountIdRouteImport
      parentRoute: typeof BudgetsBudgetIdRouteRoute
    }
  }
}

interface BudgetsBudgetIdRouteRouteChildren {
  BudgetsBudgetIdIndexRoute: typeof BudgetsBudgetIdIndexRoute
  BudgetsBudgetIdAccountsAccountIdRoute: typeof BudgetsBudgetIdAccountsAccountIdRoute
  BudgetsBudgetIdAccountsIndexRoute: typeof BudgetsBudgetIdAccountsIndexRoute
}

const BudgetsBudgetIdRouteRouteChildren: BudgetsBudgetIdRouteRouteChildren = {
  BudgetsBudgetIdIndexRoute: BudgetsBudgetIdIndexRoute,
  BudgetsBudgetIdAccountsAccountIdRoute: BudgetsBudgetIdAccountsAccountIdRoute,
  BudgetsBudgetIdAccountsIndexRoute: BudgetsBudgetIdAccountsIndexRoute,
}

const BudgetsBudgetIdRouteRouteWithChildren =
  BudgetsBudgetIdRouteRoute._addFileChildren(BudgetsBudgetIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetsBudgetIdRouteRoute: BudgetsBudgetIdRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiBudgetsRoute: ApiBudgetsRoute,
  ApiFinancialAccountsRoute: ApiFinancialAccountsRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoOrpcTodoRoute: DemoOrpcTodoRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  BudgetsIndexRoute: BudgetsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
